import numpy as np

# Define the matrix A and vectors u and v
A = np.array([[3, 1], [5, -1]])
u = np.array([6, 5])
v = np.array([-4, 1])

# Calculate the inner product <u, v>
inner_product = np.dot(np.dot(u, A), v)

print("The inner product <u, v> is:")
print(inner_product)





# Let <u, v> be the inner product on R^2 generated by A = [[3, 1], [5, -1]]. and let u = (6, 5), v = (-4, 1). Find <u, v>.