/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dentalpatientrecordsystem;

import java.awt.Color;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Marki Querequincia
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCardPanel = new javax.swing.JPanel();
        mainMenuPanel = new javax.swing.JPanel();
        mainHeader = new javax.swing.JLabel();
        displayDashBoardButton = new javax.swing.JButton();
        usersDashBoardButton = new javax.swing.JButton();
        createPanel = new javax.swing.JPanel();
        mainHeader1 = new javax.swing.JLabel();
        primaryCreatePanel = new javax.swing.JPanel();
        mainCreateLabel = new javax.swing.JLabel();
        patientInfoCreateLabel = new javax.swing.JLabel();
        givenNameCreateLabel = new javax.swing.JLabel();
        givenNameCreateText = new javax.swing.JTextField();
        lastNameCreateLabel = new javax.swing.JLabel();
        lastNameCreateText = new javax.swing.JTextField();
        middleNameCreateLabel = new javax.swing.JLabel();
        middleNameCreateText = new javax.swing.JTextField();
        ageCreateLabel = new javax.swing.JLabel();
        ageCreateText = new javax.swing.JTextField();
        civilStatusCreateLabel = new javax.swing.JLabel();
        civilStatusCreateText = new javax.swing.JTextField();
        occupationCreateLabel = new javax.swing.JLabel();
        occupationCreateText = new javax.swing.JTextField();
        contactNumCreateLabel = new javax.swing.JLabel();
        contactNumCreateText = new javax.swing.JTextField();
        addressCreateLabel = new javax.swing.JLabel();
        addressCreateText = new javax.swing.JTextField();
        patientVisitsCreateLabel = new javax.swing.JLabel();
        createCreateButton = new javax.swing.JButton();
        reasonCreateLabel = new javax.swing.JLabel();
        reasonCreateText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backCreateButton = new javax.swing.JButton();
        recordListPanel = new javax.swing.JPanel();
        mainHeader2 = new javax.swing.JLabel();
        recordListPrimaryPanel = new javax.swing.JPanel();
        editPatientRecordButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JScrollPane();
        patientRecordTable = new javax.swing.JTable();
        searchPatientLabel = new javax.swing.JLabel();
        searchPatientText = new javax.swing.JTextField();
        patientRecordsLabel = new javax.swing.JLabel();
        deletePatientRecordButton = new javax.swing.JButton();
        addPatientRecordButton = new javax.swing.JButton();
        readPatientRecordButton = new javax.swing.JButton();
        backPatientRecordButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        menuMenuBar = new javax.swing.JMenu();
        actionsMenuBar = new javax.swing.JMenu();
        searchActionMenuBar = new javax.swing.JMenuItem();
        createActionMenuBar = new javax.swing.JMenuItem();
        updateActionMenuBar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        displayActionMenuBar = new javax.swing.JMenuItem();
        usersMenuBar = new javax.swing.JMenu();
        aboutMenuBar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(86, 119, 156));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        mainCardPanel.setLayout(new java.awt.CardLayout());

        mainMenuPanel.setBackground(new java.awt.Color(64, 102, 143));
        mainMenuPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        mainHeader.setBackground(new java.awt.Color(77, 161, 190));
        mainHeader.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        mainHeader.setForeground(new java.awt.Color(255, 255, 255));
        mainHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainHeader.setText("Smile Care Dental Clinic");
        mainHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainHeader.setOpaque(true);

        displayDashBoardButton.setBackground(new java.awt.Color(77, 161, 190));
        displayDashBoardButton.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        displayDashBoardButton.setForeground(new java.awt.Color(255, 255, 255));
        displayDashBoardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marki Querequincia\\Documents\\NetBeansProjects\\DentalPatientRecordSystem\\src\\main\\java\\Icons\\clipboard.png")); // NOI18N
        displayDashBoardButton.setText("DISPLAY PATIENT RECORDS       ");
        displayDashBoardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayDashBoardButton.setFocusable(false);
        displayDashBoardButton.setOpaque(true);
        displayDashBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDashBoardButtonActionPerformed(evt);
            }
        });

        usersDashBoardButton.setBackground(new java.awt.Color(77, 161, 190));
        usersDashBoardButton.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        usersDashBoardButton.setForeground(new java.awt.Color(255, 255, 255));
        usersDashBoardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marki Querequincia\\Documents\\NetBeansProjects\\DentalPatientRecordSystem\\src\\main\\java\\Icons\\pass.png")); // NOI18N
        usersDashBoardButton.setText("  SYSTEM USER OPTIONS");
        usersDashBoardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usersDashBoardButton.setFocusable(false);
        usersDashBoardButton.setOpaque(true);
        usersDashBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersDashBoardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(536, 536, 536)
                .addComponent(displayDashBoardButton)
                .addGap(62, 62, 62)
                .addComponent(usersDashBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addComponent(mainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usersDashBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayDashBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(557, Short.MAX_VALUE))
        );

        mainCardPanel.add(mainMenuPanel, "card2");

        createPanel.setBackground(new java.awt.Color(64, 102, 143));

        mainHeader1.setBackground(new java.awt.Color(77, 161, 190));
        mainHeader1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        mainHeader1.setForeground(new java.awt.Color(255, 255, 255));
        mainHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainHeader1.setText("Smile Care Dental Clinic");
        mainHeader1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainHeader1.setOpaque(true);

        primaryCreatePanel.setBackground(new java.awt.Color(86, 119, 156));
        primaryCreatePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        primaryCreatePanel.setMaximumSize(new java.awt.Dimension(1724, 848));

        mainCreateLabel.setBackground(new java.awt.Color(77, 161, 190));
        mainCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        mainCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainCreateLabel.setText("Create New Patient Record");
        mainCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        mainCreateLabel.setOpaque(true);

        patientInfoCreateLabel.setBackground(new java.awt.Color(77, 161, 190));
        patientInfoCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        patientInfoCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientInfoCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientInfoCreateLabel.setText("Patient Information");
        patientInfoCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        patientInfoCreateLabel.setOpaque(true);

        givenNameCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        givenNameCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        givenNameCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        givenNameCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        givenNameCreateLabel.setText("Given Name:");
        givenNameCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        givenNameCreateLabel.setOpaque(true);

        givenNameCreateText.setBackground(new java.awt.Color(175, 237, 226));
        givenNameCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        givenNameCreateText.setForeground(new java.awt.Color(64, 102, 143));
        givenNameCreateText.setText("Test Text");

        lastNameCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        lastNameCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        lastNameCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastNameCreateLabel.setText("Last Name:");
        lastNameCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lastNameCreateLabel.setOpaque(true);

        lastNameCreateText.setBackground(new java.awt.Color(175, 237, 226));
        lastNameCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        lastNameCreateText.setForeground(new java.awt.Color(64, 102, 143));
        lastNameCreateText.setText("Test Text");

        middleNameCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        middleNameCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        middleNameCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        middleNameCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        middleNameCreateLabel.setText("Middle Name:");
        middleNameCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        middleNameCreateLabel.setOpaque(true);

        middleNameCreateText.setBackground(new java.awt.Color(175, 237, 226));
        middleNameCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        middleNameCreateText.setForeground(new java.awt.Color(64, 102, 143));
        middleNameCreateText.setText("Test Text");

        ageCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        ageCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        ageCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageCreateLabel.setText("Age:");
        ageCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        ageCreateLabel.setOpaque(true);

        ageCreateText.setBackground(new java.awt.Color(175, 237, 226));
        ageCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        ageCreateText.setForeground(new java.awt.Color(64, 102, 143));
        ageCreateText.setText("Test Text");

        civilStatusCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        civilStatusCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        civilStatusCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        civilStatusCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        civilStatusCreateLabel.setText("Civil Status:");
        civilStatusCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        civilStatusCreateLabel.setOpaque(true);

        civilStatusCreateText.setBackground(new java.awt.Color(175, 237, 226));
        civilStatusCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        civilStatusCreateText.setForeground(new java.awt.Color(64, 102, 143));
        civilStatusCreateText.setText("Test Text");

        occupationCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        occupationCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        occupationCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        occupationCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        occupationCreateLabel.setText("Occupation:");
        occupationCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        occupationCreateLabel.setOpaque(true);

        occupationCreateText.setBackground(new java.awt.Color(175, 237, 226));
        occupationCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        occupationCreateText.setForeground(new java.awt.Color(64, 102, 143));
        occupationCreateText.setText("Test Text");

        contactNumCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        contactNumCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        contactNumCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactNumCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactNumCreateLabel.setText("Contact #:");
        contactNumCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        contactNumCreateLabel.setOpaque(true);

        contactNumCreateText.setBackground(new java.awt.Color(175, 237, 226));
        contactNumCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        contactNumCreateText.setForeground(new java.awt.Color(64, 102, 143));
        contactNumCreateText.setText("Test Text");

        addressCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        addressCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        addressCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressCreateLabel.setText("Address:");
        addressCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        addressCreateLabel.setOpaque(true);

        addressCreateText.setBackground(new java.awt.Color(175, 237, 226));
        addressCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        addressCreateText.setForeground(new java.awt.Color(64, 102, 143));
        addressCreateText.setText("Test Text");

        patientVisitsCreateLabel.setBackground(new java.awt.Color(77, 161, 190));
        patientVisitsCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        patientVisitsCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientVisitsCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientVisitsCreateLabel.setText("Patient Visit Details");
        patientVisitsCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        patientVisitsCreateLabel.setOpaque(true);

        createCreateButton.setBackground(new java.awt.Color(77, 161, 190));
        createCreateButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        createCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        createCreateButton.setText("CREATE");
        createCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCreateButtonActionPerformed(evt);
            }
        });

        reasonCreateLabel.setBackground(new java.awt.Color(101, 191, 175));
        reasonCreateLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        reasonCreateLabel.setForeground(new java.awt.Color(255, 255, 255));
        reasonCreateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reasonCreateLabel.setText("Reason:");
        reasonCreateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        reasonCreateLabel.setOpaque(true);

        reasonCreateText.setBackground(new java.awt.Color(175, 237, 226));
        reasonCreateText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        reasonCreateText.setForeground(new java.awt.Color(64, 102, 143));
        reasonCreateText.setText("Test Text");

        jLabel1.setBackground(new java.awt.Color(153, 0, 51));
        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INCOMPLETE NOT FINAL");
        jLabel1.setOpaque(true);

        backCreateButton.setBackground(new java.awt.Color(77, 161, 190));
        backCreateButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        backCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        backCreateButton.setText("BACK");
        backCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout primaryCreatePanelLayout = new javax.swing.GroupLayout(primaryCreatePanel);
        primaryCreatePanel.setLayout(primaryCreatePanelLayout);
        primaryCreatePanelLayout.setHorizontalGroup(
            primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addComponent(middleNameCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(middleNameCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addComponent(addressCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addComponent(contactNumCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contactNumCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addComponent(ageCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ageCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addComponent(civilStatusCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(civilStatusCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addComponent(occupationCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(occupationCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientInfoCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                                .addComponent(givenNameCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(givenNameCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                                .addComponent(lastNameCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastNameCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102)
                        .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                                .addComponent(reasonCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reasonCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                                .addComponent(patientVisitsCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(476, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, primaryCreatePanelLayout.createSequentialGroup()
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(mainCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        primaryCreatePanelLayout.setVerticalGroup(
            primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryCreatePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientInfoCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientVisitsCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(givenNameCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(givenNameCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleNameCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleNameCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(civilStatusCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(civilStatusCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupationCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressCreateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressCreateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(createCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(primaryCreatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addComponent(mainHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(primaryCreatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainCardPanel.add(createPanel, "card3");

        recordListPanel.setBackground(new java.awt.Color(64, 102, 143));
        recordListPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        mainHeader2.setBackground(new java.awt.Color(77, 161, 190));
        mainHeader2.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        mainHeader2.setForeground(new java.awt.Color(255, 255, 255));
        mainHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainHeader2.setText("Smile Care Dental Clinic");
        mainHeader2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainHeader2.setOpaque(true);

        recordListPrimaryPanel.setBackground(new java.awt.Color(86, 119, 156));
        recordListPrimaryPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        editPatientRecordButton.setBackground(new java.awt.Color(77, 161, 190));
        editPatientRecordButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        editPatientRecordButton.setForeground(new java.awt.Color(255, 255, 255));
        editPatientRecordButton.setText("EDIT");
        editPatientRecordButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editPatientRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatientRecordButtonActionPerformed(evt);
            }
        });

        patientRecordTable.setBackground(new java.awt.Color(86, 119, 156));
        patientRecordTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        patientRecordTable.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        patientRecordTable.setForeground(new java.awt.Color(255, 255, 255));
        patientRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Given Name", "Last Name", "Middle Name", "Age", "Civil Status", "Occupation", "Contact #", "Address"
            }
        ));
        patientRecordTable.setRowHeight(30);
        patientRecordTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        patientRecordTable.setShowGrid(true);
        tablePanel.setViewportView(patientRecordTable);

        searchPatientLabel.setBackground(new java.awt.Color(101, 191, 175));
        searchPatientLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        searchPatientLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchPatientLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchPatientLabel.setText("Search Patient:");
        searchPatientLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        searchPatientLabel.setOpaque(true);

        searchPatientText.setBackground(new java.awt.Color(175, 237, 226));
        searchPatientText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        searchPatientText.setForeground(new java.awt.Color(64, 102, 143));
        searchPatientText.setText("Test Text");

        patientRecordsLabel.setBackground(new java.awt.Color(77, 161, 190));
        patientRecordsLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        patientRecordsLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientRecordsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientRecordsLabel.setText("All Patient Records");
        patientRecordsLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        patientRecordsLabel.setOpaque(true);

        deletePatientRecordButton.setBackground(new java.awt.Color(77, 161, 190));
        deletePatientRecordButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        deletePatientRecordButton.setForeground(new java.awt.Color(255, 255, 255));
        deletePatientRecordButton.setText("DELETE");
        deletePatientRecordButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletePatientRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatientRecordButtonActionPerformed(evt);
            }
        });

        addPatientRecordButton.setBackground(new java.awt.Color(77, 161, 190));
        addPatientRecordButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        addPatientRecordButton.setForeground(new java.awt.Color(255, 255, 255));
        addPatientRecordButton.setText("ADD NEW");
        addPatientRecordButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addPatientRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientRecordButtonActionPerformed(evt);
            }
        });

        readPatientRecordButton.setBackground(new java.awt.Color(77, 161, 190));
        readPatientRecordButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        readPatientRecordButton.setForeground(new java.awt.Color(255, 255, 255));
        readPatientRecordButton.setText("DETAILS");
        readPatientRecordButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        readPatientRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readPatientRecordButtonActionPerformed(evt);
            }
        });

        backPatientRecordButton.setBackground(new java.awt.Color(77, 161, 190));
        backPatientRecordButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        backPatientRecordButton.setForeground(new java.awt.Color(255, 255, 255));
        backPatientRecordButton.setText("BACK");
        backPatientRecordButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backPatientRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPatientRecordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordListPrimaryPanelLayout = new javax.swing.GroupLayout(recordListPrimaryPanel);
        recordListPrimaryPanel.setLayout(recordListPrimaryPanelLayout);
        recordListPrimaryPanelLayout.setHorizontalGroup(
            recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordListPrimaryPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(recordListPrimaryPanelLayout.createSequentialGroup()
                        .addComponent(patientRecordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchPatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPatientText, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordListPrimaryPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editPatientRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletePatientRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPatientRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(readPatientRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(371, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordListPrimaryPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backPatientRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        recordListPrimaryPanelLayout.setVerticalGroup(
            recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordListPrimaryPanelLayout.createSequentialGroup()
                .addGroup(recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordListPrimaryPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientRecordsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(searchPatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchPatientText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(recordListPrimaryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backPatientRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(recordListPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recordListPrimaryPanelLayout.createSequentialGroup()
                        .addComponent(readPatientRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editPatientRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletePatientRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addPatientRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout recordListPanelLayout = new javax.swing.GroupLayout(recordListPanel);
        recordListPanel.setLayout(recordListPanelLayout);
        recordListPanelLayout.setHorizontalGroup(
            recordListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(recordListPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(recordListPrimaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recordListPanelLayout.setVerticalGroup(
            recordListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordListPanelLayout.createSequentialGroup()
                .addComponent(mainHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(recordListPrimaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        mainCardPanel.add(recordListPanel, "card4");

        mainMenuBar.setBackground(new java.awt.Color(64, 102, 143));
        mainMenuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainMenuBar.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBar.setOpaque(true);
        mainMenuBar.setPreferredSize(new java.awt.Dimension(103, 26));

        menuMenuBar.setText("Menu");
        mainMenuBar.add(menuMenuBar);

        actionsMenuBar.setText("Actions");

        searchActionMenuBar.setText("Search Patient Record");
        actionsMenuBar.add(searchActionMenuBar);

        createActionMenuBar.setText("Create Patient Record");
        actionsMenuBar.add(createActionMenuBar);

        updateActionMenuBar.setText("Update Patient Record");
        actionsMenuBar.add(updateActionMenuBar);

        jMenuItem1.setText("Delete Patient Record");
        actionsMenuBar.add(jMenuItem1);

        displayActionMenuBar.setText("Display Patient Record List");
        actionsMenuBar.add(displayActionMenuBar);

        mainMenuBar.add(actionsMenuBar);

        usersMenuBar.setText("Users");
        mainMenuBar.add(usersMenuBar);

        aboutMenuBar.setText("About");
        mainMenuBar.add(aboutMenuBar);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayDashBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDashBoardButtonActionPerformed
        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
            cl.show(mainCardPanel, "card4");
    }//GEN-LAST:event_displayDashBoardButtonActionPerformed

    private void usersDashBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersDashBoardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersDashBoardButtonActionPerformed

    private void createCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCreateButtonActionPerformed

    private void editPatientRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatientRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPatientRecordButtonActionPerformed

    private void deletePatientRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatientRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePatientRecordButtonActionPerformed

    private void addPatientRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientRecordButtonActionPerformed
        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
            cl.show(mainCardPanel, "card3");
    }//GEN-LAST:event_addPatientRecordButtonActionPerformed

    private void readPatientRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readPatientRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readPatientRecordButtonActionPerformed

    private void backPatientRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPatientRecordButtonActionPerformed
        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
            cl.show(mainCardPanel, "card2");
    }//GEN-LAST:event_backPatientRecordButtonActionPerformed

    private void backCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCreateButtonActionPerformed
        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
            cl.show(mainCardPanel, "card2");
    }//GEN-LAST:event_backCreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenuBar;
    private javax.swing.JMenu actionsMenuBar;
    private javax.swing.JButton addPatientRecordButton;
    private javax.swing.JLabel addressCreateLabel;
    private javax.swing.JTextField addressCreateText;
    private javax.swing.JLabel ageCreateLabel;
    private javax.swing.JTextField ageCreateText;
    private javax.swing.JButton backCreateButton;
    private javax.swing.JButton backPatientRecordButton;
    private javax.swing.JLabel civilStatusCreateLabel;
    private javax.swing.JTextField civilStatusCreateText;
    private javax.swing.JLabel contactNumCreateLabel;
    private javax.swing.JTextField contactNumCreateText;
    private javax.swing.JMenuItem createActionMenuBar;
    private javax.swing.JButton createCreateButton;
    private javax.swing.JPanel createPanel;
    private javax.swing.JButton deletePatientRecordButton;
    private javax.swing.JMenuItem displayActionMenuBar;
    private javax.swing.JButton displayDashBoardButton;
    private javax.swing.JButton editPatientRecordButton;
    private javax.swing.JLabel givenNameCreateLabel;
    private javax.swing.JTextField givenNameCreateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lastNameCreateLabel;
    private javax.swing.JTextField lastNameCreateText;
    private javax.swing.JPanel mainCardPanel;
    private javax.swing.JLabel mainCreateLabel;
    private javax.swing.JLabel mainHeader;
    private javax.swing.JLabel mainHeader1;
    private javax.swing.JLabel mainHeader2;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JMenu menuMenuBar;
    private javax.swing.JLabel middleNameCreateLabel;
    private javax.swing.JTextField middleNameCreateText;
    private javax.swing.JLabel occupationCreateLabel;
    private javax.swing.JTextField occupationCreateText;
    private javax.swing.JLabel patientInfoCreateLabel;
    private javax.swing.JTable patientRecordTable;
    private javax.swing.JLabel patientRecordsLabel;
    private javax.swing.JLabel patientVisitsCreateLabel;
    private javax.swing.JPanel primaryCreatePanel;
    private javax.swing.JButton readPatientRecordButton;
    private javax.swing.JLabel reasonCreateLabel;
    private javax.swing.JTextField reasonCreateText;
    private javax.swing.JPanel recordListPanel;
    private javax.swing.JPanel recordListPrimaryPanel;
    private javax.swing.JMenuItem searchActionMenuBar;
    private javax.swing.JLabel searchPatientLabel;
    private javax.swing.JTextField searchPatientText;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JMenuItem updateActionMenuBar;
    private javax.swing.JButton usersDashBoardButton;
    private javax.swing.JMenu usersMenuBar;
    // End of variables declaration//GEN-END:variables

    
    public void displayForm() {
        // Set the visibility of the form to true
        setVisible(true);
        
    }
}

