/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dentalpatientrecordsystem;

/**
 *
 * @author Marki Querequincia
 */
public class loginPopUp extends javax.swing.JFrame {

    /**
     * Creates new form loginPopUp
     */
    public loginPopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginClinicLabel = new javax.swing.JLabel();
        loginPrimaryPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        usernameLoginLabel = new javax.swing.JLabel();
        usernameLoginText = new javax.swing.JTextField();
        passwordLoginLabel = new javax.swing.JLabel();
        backCreateButton = new javax.swing.JButton();
        passwordLoginText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 450));
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(64, 102, 143));

        loginClinicLabel.setBackground(new java.awt.Color(77, 161, 190));
        loginClinicLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        loginClinicLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginClinicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginClinicLabel.setText("SMILE CARE DENTAL CLINIC");
        loginClinicLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginClinicLabel.setOpaque(true);

        loginPrimaryPanel.setBackground(new java.awt.Color(86, 119, 156));
        loginPrimaryPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        loginLabel.setBackground(new java.awt.Color(77, 161, 190));
        loginLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("LOG IN");
        loginLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginLabel.setOpaque(true);

        usernameLoginLabel.setBackground(new java.awt.Color(101, 191, 175));
        usernameLoginLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        usernameLoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLoginLabel.setText("USERNAME:");
        usernameLoginLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        usernameLoginLabel.setOpaque(true);

        usernameLoginText.setBackground(new java.awt.Color(175, 237, 226));
        usernameLoginText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        usernameLoginText.setText("TEST TEXT");

        passwordLoginLabel.setBackground(new java.awt.Color(101, 191, 175));
        passwordLoginLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        passwordLoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLoginLabel.setText("PASSWORD:");
        passwordLoginLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        passwordLoginLabel.setOpaque(true);

        backCreateButton.setBackground(new java.awt.Color(77, 161, 190));
        backCreateButton.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        backCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        backCreateButton.setText("login");
        backCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCreateButtonActionPerformed(evt);
            }
        });

        passwordLoginText.setBackground(new java.awt.Color(175, 237, 226));
        passwordLoginText.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        passwordLoginText.setText("TEST TEXT");

        javax.swing.GroupLayout loginPrimaryPanelLayout = new javax.swing.GroupLayout(loginPrimaryPanel);
        loginPrimaryPanel.setLayout(loginPrimaryPanelLayout);
        loginPrimaryPanelLayout.setHorizontalGroup(
            loginPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPrimaryPanelLayout.createSequentialGroup()
                .addGroup(loginPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPrimaryPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPrimaryPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(loginPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginPrimaryPanelLayout.createSequentialGroup()
                                .addComponent(usernameLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameLoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPrimaryPanelLayout.createSequentialGroup()
                                .addComponent(passwordLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordLoginText))))
                    .addGroup(loginPrimaryPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(backCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        loginPrimaryPanelLayout.setVerticalGroup(
            loginPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPrimaryPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(loginPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(usernameLoginText))
                .addGap(18, 18, 18)
                .addGroup(loginPrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(passwordLoginText))
                .addGap(57, 57, 57)
                .addComponent(backCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginClinicLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPrimaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(loginClinicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPrimaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCreateButtonActionPerformed
        DashBoard dashBoard = new DashBoard();
        dashBoard.displayForm();
        
        this.dispose();
    }//GEN-LAST:event_backCreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backCreateButton;
    private javax.swing.JLabel loginClinicLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel loginPrimaryPanel;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JPasswordField passwordLoginText;
    private javax.swing.JLabel usernameLoginLabel;
    private javax.swing.JTextField usernameLoginText;
    // End of variables declaration//GEN-END:variables
    
    public void displayForm() {
        // Set the visibility of the form to true
        setVisible(true); 
    }
}
